name: Maven Project Info

outputs:
  project_name:
    description: The name of the project
    value: openapi-java-client-codegen
  project_version:
    description: The version of the project
    value: ${{ steps.get_project_info.outputs.version }}

runs:
  using: composite
  steps:
    - name: Get Project Info
      id: get_project_info
      shell: bash
      run: ${{ github.action_path }}/get-project-info.sh