#!/bin/bash

set -euo pipefail

run() {
  echo "Running spotless pre-commit check..."

  IFS=$'\n'
  pre_format_files=($(git diff --name-only --staged))
  mvn -P source-and-tests spotless:apply

  for pre_file in "${pre_format_files[@]}"; do
    if [ -f "$pre_file" ]; then
      echo "Re-adding spotless formatted file: to git $pre_file"
      git add "$pre_file"
    fi
  done
}

run