name: Docker Build

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      image_tag:
        type: string
        required: true
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: project_artifacts
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          # TODO document these in the readme
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: false # TODO make this true in the real thing
          tags: rlidev/${{ inputs.image_name }}:${{ inputs.image_tag }} # TODO make this the real repo/tag
          context: .
          platforms: linux/amd64,linux/arm64