name: Pull Request

on:
  pull_request:
    branches: [ 'main' ]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  run_maven_build:
    uses: ./.github/workflows/core-maven-build.yml
    with:
      is_release: false